name: Generate Snake

on:
  schedule:
    - cron: "0 3 * * *"  # meia-noite no Brasil
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Flavinha-Souza
          outputs: |
            dist/snake.svg 
            dist/snake-dark.svg?palette=github-dark&color_snake=%23a78bfa&color_dots=%233b0764,%235b21b6,%237c3aed

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
